[package]
name = "html-languageservice"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
lsp-textdocument = "0.3.1"
lsp-types = "0.94.1"
regex = "1.9.5"
serde = "1.0.188"
serde_json = "1.0.107"
unicode-segmentation = "1.10.1"
